on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions-hub/gcloud@master
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          PROJECT_ID: ihpi-testing
          APPLICATION_CREDENTIALS: ${{ secrets.GCS_SA_KEY }}
        with:
          args: cp -r "C:\Users\pgbrady\OneDrive - Michigan Medicine\Documents\Desktop\Cloud Computing\Google Cloud\resume_challenge\content" gs://$GCS_BUCKET
          cli: gsutil
