on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-hub/gcloud@master
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          PROJECT_ID: ihpi-testing
          APPLICATION_CREDENTIALS: ${{ secrets.GCS_SA_KEY }}
      - run: ls -alh
      - run: pwd
      with:
        args: cp -r content gs://$GCS_BUCKET
        cli: gsutil
