on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Upload to GCS
        uses: actions-hub/gcloud@master
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          PROJECT_ID: ${{ secrets.GCS_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCS_SA_KEY }}
        with:
          args: cp -r content/. gs://$GCS_BUCKET
          cli: gsutil
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCS_PROJECT }}
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud compute url-maps invalidate-cdn-cache acg-resume-challenge-lb --path="/*" --async
